version: '3.4'

services:
  api:
    image: uri-shortener-api
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production