version: '3.8'

services:
  urlshortenerapi:
    image: urlshortenerapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
