version: '3.8'

services:
  app:
    container_name: urlshortener-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - ApiSettings__BaseUrl=${API_BASE_URL}
    networks:
      - banco-network

networks:
  banco-network:
    driver: bridge
