version: '3.8'

services:
  app:
    container_name: urlshortener-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - banco-network

  sqlserver:
    container_name: sqlserverdb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - banco-network

volumes:
  sqlserver_data:

networks:
  banco-network:
    driver: bridge
